language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.0
jdk: 'openjdk8'

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install:
    - gem install -v 1.17.2 bundler
    - bundle _1.17.2_ install