language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.4
jdk: 'oraclejdk8'
matrix:
  include:
    - rvm: 2.1.5

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
