development:
  :url: http://127.0.0.1:8983/fedora
  :user: fedoraAdmin
  :password: fedoraAdmin
test:
  :url: http://127.0.0.1:8983/fedora
  :user: fedoraAdmin
  :password: fedoraAdmin
default:
  :url: http://127.0.0.1:8983/fedora
  :user: fedoraAdmin
  :password: fedoraAdmin
