development:
  default:
    url: http://127.0.0.1:8983/solr/development
  full_text:
    url: http://127.0.0.1:8983/solr/development
test:
  default:
    url: http://127.0.0.1:8983/solr/test
  full_text:
    url: http://127.0.0.1:8983/solr/test
default:
  default:
    url: http://127.0.0.1:8983/solr/test
  full_text:
    url: http://127.0.0.1:8983/solr/test
