:marc_to_facet :
  'NNC-A' : 'Avery'
  'NNC-ART' : 'Office of Art Properties'
  'NNBa' : 'Barnard College Library'
  'NNC-EA' : 'East Asian'
  'NNC-L' : 'Law Library'
  'NNC-M' : 'Health Sciences Library'
  'NNC-MUS' : 'Music Library'
  'NNC-RB' : 'RBML'
  'NyNyCBL' : 'Burke Library'
  'NyNyCOH' : 'CCOH'
:marc_to_display :
  'NNC-A' : 'Avery Architectural & Fine Arts Library'
  'NNC-ART' : 'Office of Art Properties'
  'NNBa' : 'Barnard College Library'
  'NNC-EA' : 'Starr East Asian'
  'NNC-L' : 'Law Library'
  'NNC-M' : 'Health Sciences Library'
  'NNC-MUS' : 'Music Library'
  'NNC-RB' : 'Rare Book and Manuscript Library'
  'NyNyCBL' : 'Burke Library at Union Theological Seminary'
  'NyNyCOH' : 'Columbia Center for Oral History Collections'
:project_facet :
  'Customer Order Collection' : 'Pres Orders'
  "Children's Drawings of the Spanish Civil War (online exhibition)" : 'Spanish Civil War'
  "Jewels in her crown: treasures of Columbia University Libraries special collections" : 'Jewels in her Crown'
  "Russian Imperial Corps of Pages" : 'Russian Corps of Pages'
