version: "3.9"

# Although a name isn't required for docker to work, we want to explicitly specify it so we know
# which prefix is used for the volumes that we create.
name: 'cul_hydra-test'

volumes:
  redis-data:
  solr-cores:
  fedora-install-dir:
services:
  redis:
    build: ./redis
    restart: always
    ports:
      - '7379:6379'
    volumes:
      - redis-data:/data
  solr:
    build: ./solr
    restart: always
    ports:
      - '9983:8983'
    volumes:
      - solr-cores:/data
  fedora:
    build: ./fedora
    restart: always
    ports:
      - '9080:8080'
    volumes:
      - fedora-install-dir:/opt/fedora
