# -*- encoding: utf-8 -*-
# This file generated automatically using vocab-fetch from http://www.semanticdesktop.org/ontologies/2007/01/19/nie
require 'rdf'
module RDF
  class NIE < RDF::StrictVocabulary("http://www.semanticdesktop.org/ontologies/2007/01/19/nie")

    # Class definitions
    term :"#DataObject",
      comment: %(A unit of data that is created, annotated and processed on the user desktop. It represents a native structure the user works with. The usage of the term 'native' is important. It means that a DataObject can be directly mapped to a data structure maintained by a native application. This may be a file, a set of files or a part of a file. The granularity depends on the user. This class is not intended to be instantiated by itself. Use more specific subclasses.).freeze,
      label: "DataObject".freeze,
      subClassOf: "rdfs:Resource".freeze,
      type: "rdfs:Class".freeze
    term :"#DataSource",
      comment: %(A superclass for all entities from which DataObjects can be extracted. Each entity represents a native application or some other system that manages information that may be of interest to the user of the Semantic Desktop. Subclasses may include FileSystems, Mailboxes, Calendars, websites etc. The exact choice of subclasses and their properties is considered application-specific. Each data extraction application is supposed to provide it's own DataSource ontology. Such an ontology should contain supported data source types coupled with properties necessary for the application to gain access to the data sources.  \(paths, urls, passwords  etc...\)).freeze,
      label: "DataSource".freeze,
      subClassOf: "rdfs:Resource".freeze,
      type: "rdfs:Class".freeze
    term :"#InformationElement",
      comment: %(A unit of content the user works with. This is a superclass for all interpretations of a DataObject.).freeze,
      label: "InformationElement".freeze,
      subClassOf: "rdfs:Resource".freeze,
      type: "rdfs:Class".freeze
    term :"#Mode",
      comment: %(Representation for a standard set of device/application/service modes, corresponding to various sets of modes that are either inbuilt in a device \(e.g. inbuilt phone modes such as silent, loud, general, vibrate, etc.\) or available for applications and online services \(e.g. IM system modes such as busy, available, invisible, etc.\)).freeze,
      label: "Mode".freeze,
      type: "rdfs:Class".freeze

    # Property definitions
    property :"#byteSize",
      comment: %(The overall size of the data object in bytes. That means the space taken by the DataObject in its container, and not the size of the content that is of interest to the user. For cases where the content size is different \(e.g. in compressed files the content is larger, in messages the content excludes headings and is smaller\) use more specific properties, not necessarily subproperties of this one.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "byteSize".freeze,
      range: "xsd:integer".freeze,
      type: "rdf:Property".freeze
    property :"#characterSet",
      comment: %(Characterset in which the content of the InformationElement was created. Example: ISO-8859-1, UTF-8. One of the registered character sets at http://www.iana.org/assignments/character-sets. This characterSet is used to interpret any textual parts of the content. If more than one characterSet is used within one data object, use more specific properties.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "characterSet".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#comment",
      comment: %(A user comment about an InformationElement.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "comment".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#contentCreated",
      comment: %(The date of the content creation. This may not necessarily be equal to the date when the DataObject \(i.e. the physical representation\) itself was created. Compare with nie:created property.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "contentCreated".freeze,
      range: "xsd:dateTime".freeze,
      subPropertyOf: ["http://www.semanticdesktop.org/ontologies/2007/01/19/nie#informationElementDate".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#created".freeze, "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#contentModified".freeze],
      type: "rdf:Property".freeze
    property :"#contentLastModified",
      comment: %(The date of the last modification of the original content \(not its corresponding DataObject or local copy\). Compare with nie:lastModified.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "contentLastModified".freeze,
      range: "xsd:dateTime".freeze,
      subPropertyOf: ["http://www.semanticdesktop.org/ontologies/2007/01/19/nie#informationElementDate".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#lastModified".freeze, "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#contentModified".freeze],
      type: "rdf:Property".freeze
    property :"#contentModified",
      comment: %(The date of a modification of the original content \(not its corresponding DataObject or local copy\). Compare with nie:modified.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "modified".freeze,
      range: "xsd:dateTime".freeze,
      type: "rdf:Property".freeze
    property :"#contentSize",
      comment: %(The size of the content. This property can be used whenever the size of the content of an InformationElement differs from the size of the DataObject. \(e.g. because of compression, encoding, encryption or any other representation issues\). The contentSize in expressed in bytes.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "contentSize".freeze,
      range: "xsd:integer".freeze,
      type: "rdf:Property".freeze
    property :"#copyright",
      comment: %(Content copyright).freeze,
      label: "copyright".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: ["http://www.semanticdesktop.org/ontologies/2007/01/19/nie#legal".freeze, "dc:accessRights".freeze],
      type: "rdf:Property".freeze
    property :"#coreGraph",
      comment: %(Connects the data object with the graph that contains information about it. Deprecated in favor of a more generic nao:isDataGraphFor.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#deprecated" => %(true).freeze,
      label: "coreGraph".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#InstanceBase".freeze,
      type: "rdf:Property".freeze
    property :"#created",
      comment: %(Date of creation of the DataObject. Note that this date refers to the creation of the DataObject itself \(i.e. the physical representation\). Compare with nie:contentCreated.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "created".freeze,
      range: "xsd:dateTime".freeze,
      subPropertyOf: ["dc:created".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#created".freeze, "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#modified".freeze],
      type: "rdf:Property".freeze
    property :"#dataSource",
      comment: %(Marks the provenance of a DataObject, what source does a data object come from.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#minCardinality" => %(1).freeze,
      label: "dataSource".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource".freeze,
      subPropertyOf: "dc11:source".freeze,
      type: "rdf:Property".freeze
    property :"#depends",
      comment: %(Dependency relation. A piece of content depends on another piece of data in order to be properly understood/used/interpreted.).freeze,
      label: "depends".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      subPropertyOf: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#relatedTo".freeze,
      type: "rdf:Property".freeze
    property :"#description",
      comment: %(A textual description of the resource. This property may be used for any metadata fields that provide some meta-information or comment about a resource in the form of a passage of text. This property is not to be confused with nie:plainTextContent. Use more specific subproperties wherever possible.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "description".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: ["dc11:description".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#description".freeze],
      type: "rdf:Property".freeze
    property :"#disclaimer",
      comment: %(A disclaimer).freeze,
      label: "disclaimer".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#legal".freeze,
      type: "rdf:Property".freeze
    property :"#generator",
      comment: %(Software used to "generate" the contents. E.g. a word processor name.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "generator".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#generatorOption",
      comment: %(A common superproperty for all settings used by the generating software. This may include compression settings, algorithms, autosave, interlaced/non-interlaced etc. Note that this property has no range specified and therefore should not be used directly. Always use more specific properties.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "generatorOption".freeze,
      type: "rdf:Property".freeze
    property :"#hasLogicalPart",
      comment: %(Generic property used to express 'logical' containment relationships between InformationElements. NIE extensions are encouraged to provide more specific subproperties of this one. It is advisable for actual instances of InformationElement to use those specific subproperties. Note the difference between 'physical' containment \(hasPart\) and logical containment \(hasLogicalPart\)).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty" => %(http://www.semanticdesktop.org/ontologies/2007/01/19/nie#isLogicalPartOf).freeze,
      label: "hasLogicalPart".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      subPropertyOf: "dc:hasPart".freeze,
      type: "rdf:Property".freeze
    property :"#hasPart",
      comment: %(Generic property used to express 'physical' containment relationships between DataObjects. NIE extensions are encouraged to provide more specific subproperties of this one. It is advisable for actual instances of DataObjects to use those specific subproperties. Note to the developers: Please be aware of the distinction between containment relation and provenance. The hasPart relation models physical containment, an InformationElement \(a nmo:Message\) can have a 'physical' part \(an nfo:Attachment\).  Also, please note the difference between physical containment \(hasPart\) and logical containment \(hasLogicalPart\) the former has more strict meaning. They may occur independently of each other.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#userVisible" => %(false).freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty" => %(http://www.semanticdesktop.org/ontologies/2007/01/19/nie#isPartOf).freeze,
      label: "hasPart".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      subPropertyOf: ["http://www.semanticdesktop.org/ontologies/2007/01/19/nie#relatedTo".freeze, "dc:hasPart".freeze],
      type: ["rdf:Property".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#InverseFunctionalProperty".freeze]
    property :"#htmlContent",
      comment: %(The HTML content of an information element. This property can be used to store text including formatting in a generic fashion.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "html content".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#identifier",
      comment: %(An unambiguous reference to the InformationElement within a given context. Recommended best practice is to identify the resource by means of a string conforming to a formal identification system.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "identifier".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: ["http://www.semanticdesktop.org/ontologies/2007/08/15/nao#identifier".freeze, "dc11:identifier".freeze],
      type: "rdf:Property".freeze
    property :"#informationElementDate",
      comment: %(A point or period of time associated with an event in the lifecycle of an Information Element. A common superproperty for all date-related properties of InformationElements in the NIE Framework.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "informationElementDate".freeze,
      range: "xsd:dateTime".freeze,
      subPropertyOf: "dc11:date".freeze,
      type: "rdf:Property".freeze
    property :"#interpretedAs",
      comment: %(Links the DataObject with the InformationElement it is interpreted as.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty" => %(http://www.semanticdesktop.org/ontologies/2007/01/19/nie#isStoredAs).freeze,
      label: "interpretedAs".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      type: "rdf:Property".freeze
    property :"#isLogicalPartOf",
      comment: %(Generic property used to express 'logical' containment relationships between DataObjects. NIE extensions are encouraged to provide more specific subproperties of this one. It is advisable for actual instances of InformationElement to use those specific subproperties. Note the difference between 'physical' containment \(isPartOf\) and logical containment \(isLogicalPartOf\)).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty" => %(http://www.semanticdesktop.org/ontologies/2007/01/19/nie#hasLogicalPart).freeze,
      label: "isLogicalPartOf".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      subPropertyOf: "dc:isPartOf".freeze,
      type: ["rdf:Property".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DefiningProperty".freeze]
    property :"#isPartOf",
      comment: %(Generic property used to express containment relationships between DataObjects. NIE extensions are encouraged to provide more specific subproperties of this one. It is advisable for actual instances of DataObjects to use those specific subproperties. Note to the developers: Please be aware of the distinction between containment relation and provenance. The isPartOf relation models physical containment, a nie:DataObject \(e.g. an nfo:Attachment\) is a 'physical' part of an nie:InformationElement \(a nmo:Message\). Also, please note the difference between physical containment \(isPartOf\) and logical containment \(isLogicalPartOf\) the former has more strict meaning. They may occur independently of each other.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#userVisible" => %(false).freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty" => %(http://www.semanticdesktop.org/ontologies/2007/01/19/nie#hasPart).freeze,
      label: "isPartOf".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      subPropertyOf: "dc:isPartOf".freeze,
      type: ["rdf:Property".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#FunctionalProperty".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DefiningProperty".freeze]
    property :"#isStoredAs",
      comment: %(Links the information element with the DataObject it is stored in.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#inverseProperty" => %(http://www.semanticdesktop.org/ontologies/2007/01/19/nie#interpretedAs).freeze,
      label: "isStoredAs".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      type: "rdf:Property".freeze
    property :"#keyword",
      comment: %(Adapted DublinCore: The topic of the content of the resource, as keyword. No sentences here. Recommended best practice is to select a value from a controlled vocabulary or formal classification scheme. ).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "keyword".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#language",
      comment: %(Language the InformationElement is expressed in. This property applies to the data object in its entirety. If the data object is divisible into parts expressed in multiple languages - more specific properties should be used. Users are encouraged to use the two-letter code specified in the RFC 3066).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "language".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: "dc11:language".freeze,
      type: "rdf:Property".freeze
    property :"#lastModified",
      comment: %(Last modification date of the DataObject. Note that this date refers to the modification of the DataObject itself \(i.e. the physical representation\). Compare with nie:contentLastModified.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "lastModified".freeze,
      range: "xsd:dateTime".freeze,
      subPropertyOf: ["dc11:date".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#lastModified".freeze, "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#modified".freeze],
      type: "rdf:Property".freeze
    property :"#lastRefreshed",
      comment: %(Date when information about this data object was retrieved \(for the first time\) or last refreshed from the data source. This property is important for metadata extraction applications that don't receive any notifications of changes in the data source and have to poll it regularly. This may lead to information becoming out of date. In these cases this property may be used to determine the age of data, which is an important element of it's dependability. ).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "lastRefreshed".freeze,
      range: "xsd:dateTime".freeze,
      subPropertyOf: "dc11:date".freeze,
      type: "rdf:Property".freeze
    property :"#legal",
      comment: %(A common superproperty for all properties that point at legal information about an Information Element).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "legal".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: "dc11:rights".freeze,
      type: "rdf:Property".freeze
    property :"#license",
      comment: %(Terms and intellectual property rights licensing conditions.).freeze,
      label: "license".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: ["dc:license".freeze, "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#legal".freeze],
      type: "rdf:Property".freeze
    property :"#licenseType",
      comment: %(The type of the license. Possible values for this field may include "GPL", "BSD", "Creative Commons" etc.).freeze,
      label: "licenseType".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#legal".freeze,
      type: "rdf:Property".freeze
    property :"#links",
      comment: %(A linking relation. A piece of content links/mentions a piece of data).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "links".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      subPropertyOf: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#relatedTo".freeze,
      type: "rdf:Property".freeze
    property :"#mimeType",
      comment: %(The mime type of the resource, if available. Example: "text/plain". See http://www.iana.org/assignments/media-types/. This property applies to data objects that can be described with one mime type. In cases where the object as a whole has one mime type, while it's parts have other mime types, or there is no mime type that can be applied to the object as a whole, but some parts of the content have mime types - use more specific properties.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "mimeType".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#modified",
      comment: %(Date the DataObject was changed in any way.  Note that this date refers to the modification of the DataObject itself \(i.e. the physical representation\). Compare with nie:contentModified.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      label: "modified".freeze,
      range: "xsd:dateTime".freeze,
      type: "rdf:Property".freeze
    property :"#plainTextContent",
      comment: %(Plain-text representation of the content of a InformationElement with all markup removed. The main purpose of this property is full-text indexing and search. Its exact content is considered application-specific. The user can make no assumptions about what is and what is not contained within. Applications should use more specific properties wherever possible.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "plainTextContent".freeze,
      range: "xsd:string".freeze,
      type: "rdf:Property".freeze
    property :"#relatedTo",
      comment: %(A common superproperty for all relations between a piece of content and other pieces of data \(which may be interpreted as other pieces of content\).).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "relatedTo".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      subPropertyOf: "dc11:relation".freeze,
      type: "rdf:Property".freeze
    property :"#rootElementOf",
      comment: %(DataObjects extracted from a single data source are organized into a containment tree. This property links the root of that tree with the datasource it has been extracted from).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "rootElementOf".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource".freeze,
      type: "rdf:Property".freeze
    property :"#sourceMode",
      comment: %(Represents a number of applicable modes for a data source.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataSource".freeze,
      label: "Data Source Mode".freeze,
      range: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#Mode".freeze,
      type: "rdf:Property".freeze
    property :"#subject",
      comment: %(An overall topic of the content of a InformationElement).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "subject".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: "dc11:subject".freeze,
      type: "rdf:Property".freeze
    property :"#title",
      comment: %(Name given to an InformationElement).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "title".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: ["dc11:title".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nao#prefLabel".freeze],
      type: "rdf:Property".freeze
    property :"#url",
      comment: %(URL of a DataObject. It points to the location of the object. A typial usage is FileDataObject. In cases where creating a simple file:// or http:// URL for a file is difficult \(e.g. for files inside compressed archives\) the applications are encouraged to use conventions defined by Apache Commons VFS Project at http://jakarta.apache.org/  commons/ vfs/ filesystems.html.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#DataObject".freeze,
      "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#maxCardinality" => %(1).freeze,
      label: "url".freeze,
      range: "rdfs:Resource".freeze,
      type: ["rdf:Property".freeze, "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#DefiningProperty".freeze]
    property :"#version",
      comment: %(The current version of the given data object. Exact semantics is unspecified at this level. Use more specific subproperties if needed.).freeze,
      domain: "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#InformationElement".freeze,
      label: "version".freeze,
      range: "xsd:string".freeze,
      subPropertyOf: "dc:hasVersion".freeze,
      type: "rdf:Property".freeze

    # Extra definitions
    term :"#DataSourceGraph",
      comment: %(Represents the sum of all information that has been obtained from a data source. Each data source has its own personal information graph. When a data source is deleted, the graph becomes redundant and should also be deleted. If two or more items in two or more data source graphs are determined to be equivalent, they are integrated at the PIMO level, and the integrated representation plus the links to the original items are stored in the pimo:PersonalInformationModel graph.).freeze,
      label: "Data Source Graph".freeze,
      subClassOf: "http://www.semanticdesktop.org/ontologies/2007/08/15/nrl#InstanceBase".freeze,
      type: "rdfs:Resource".freeze
  end
end
